create table if not exists public.invoice_collections (
  id bigint generated by default as identity primary key,
  invoice_id text not null,
  invoice_no text not null,
  customer_code text,
  customer_name text not null,
  collection_date date not null,
  amount numeric(14,2) not null check (amount > 0),
  payment_method text not null default 'BANK_TRANSFER'
    check (payment_method in ('CASH', 'BANK_TRANSFER', 'CHEQUE', 'OTHER')),
  cheque_status text,
  cheque_status_date date,
  reference_no text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists invoice_collections_invoice_id_idx
  on public.invoice_collections (invoice_id);
create index if not exists invoice_collections_invoice_no_idx
  on public.invoice_collections (invoice_no);
create index if not exists invoice_collections_customer_name_idx
  on public.invoice_collections (customer_name);
create index if not exists invoice_collections_collection_date_idx
  on public.invoice_collections (collection_date desc);

alter table public.invoice_collections enable row level security;

alter table public.invoice_collections
  add column if not exists transfer_fees numeric(14,2) not null default 0
  check (transfer_fees >= 0);

alter table public.invoice_collections
  add column if not exists cash_fraction numeric(14,2) not null default 0
  check (cash_fraction >= 0),
  add column if not exists wht_deducted_amount numeric(14,2) not null default 0
  check (wht_deducted_amount >= 0);

alter table public.invoice_collections
  add column if not exists cheque_status text,
  add column if not exists cheque_status_date date;

update public.invoice_collections
set cheque_status = 'IN_TREASURY',
    cheque_status_date = coalesce(cheque_status_date, collection_date)
where payment_method = 'CHEQUE' and cheque_status is null;

update public.invoice_collections
set cheque_status = null, cheque_status_date = null
where payment_method <> 'CHEQUE';

alter table public.invoice_collections
  drop constraint if exists invoice_collections_cheque_status_check;
alter table public.invoice_collections
  add constraint invoice_collections_cheque_status_check check (
    (payment_method = 'CHEQUE' and cheque_status in ('IN_TREASURY', 'UNDER_COLLECTION', 'COLLECTED', 'REFUSED', 'RETURNED_TO_CUSTOMER'))
    or (payment_method <> 'CHEQUE' and cheque_status is null)
  );

update public.dashboard_users
set permissions = jsonb_set(
  coalesce(permissions, '{}'::jsonb),
  '{collections}',
  '{"view":false,"edit":false}'::jsonb,
  true
)
where not coalesce(permissions, '{}'::jsonb) ? 'collections';

update public.dashboard_users
set permissions = jsonb_set(
  coalesce(permissions, '{}'::jsonb),
  '{cheques}',
  '{"view":false,"edit":false}'::jsonb,
  true
)
where not coalesce(permissions, '{}'::jsonb) ? 'cheques';

-- One cheque may settle multiple invoices. The cheque is stored once and its
-- amount is distributed through allocation rows.
create table if not exists public.customer_cheques (
  id bigint generated by default as identity primary key,
  customer_code text,
  customer_name text not null,
  collection_date date not null,
  cheque_no text not null,
  bank_name text not null default '',
  cheque_date date not null,
  amount numeric(14,2) not null check (amount > 0),
  cheque_status text not null default 'IN_TREASURY'
    check (cheque_status in ('IN_TREASURY', 'UNDER_COLLECTION', 'COLLECTED', 'REFUSED', 'RETURNED_TO_CUSTOMER')),
  cheque_status_date date not null,
  notes text,
  legacy_collection_id bigint unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_code, cheque_no)
);

create table if not exists public.cheque_allocations (
  id bigint generated by default as identity primary key,
  cheque_id bigint not null references public.customer_cheques(id) on delete cascade,
  invoice_id text not null,
  invoice_no text not null,
  allocated_amount numeric(14,2) not null check (allocated_amount > 0),
  wht_deducted_amount numeric(14,2) not null default 0 check (wht_deducted_amount >= 0),
  created_at timestamptz not null default now(),
  unique (cheque_id, invoice_id)
);

create index if not exists customer_cheques_status_idx on public.customer_cheques (cheque_status, cheque_status_date desc);
create index if not exists customer_cheques_customer_idx on public.customer_cheques (customer_name);
create index if not exists cheque_allocations_invoice_idx on public.cheque_allocations (invoice_id);
create index if not exists cheque_allocations_cheque_idx on public.cheque_allocations (cheque_id);

alter table public.customer_cheques enable row level security;
alter table public.cheque_allocations enable row level security;

alter table public.cheque_allocations
  add column if not exists wht_deducted_amount numeric(14,2) not null default 0
  check (wht_deducted_amount >= 0);

alter table public.cheque_allocations
  add column if not exists cash_fraction numeric(14,2) not null default 0
  check (cash_fraction >= 0);

-- Close historical sub-pound balances on invoices whose final settlement was
-- a collected cheque. The fraction is stored separately and never increases
-- the cheque amount or the customer's cash payment.
with direct_settlement as (
  select invoice_id,
    coalesce(sum(amount + cash_fraction), 0) as payments,
    coalesce(sum(wht_deducted_amount), 0) as deducted_wht
  from public.invoice_collections
  where payment_method <> 'CHEQUE'
  group by invoice_id
), collected_cheque_settlement as (
  select allocation.invoice_id,
    coalesce(sum(allocation.allocated_amount + allocation.cash_fraction), 0) as payments,
    coalesce(sum(allocation.wht_deducted_amount), 0) as deducted_wht,
    max(allocation.id) as final_allocation_id
  from public.cheque_allocations allocation
  join public.customer_cheques cheque on cheque.id = allocation.cheque_id
  where cheque.cheque_status = 'COLLECTED'
  group by allocation.invoice_id
), recorded_wht as (
  select invoice_no, coalesce(sum(wht_amount), 0) as amount
  from public.wht_collections
  group by invoice_no
), residuals as (
  select cheque.final_allocation_id,
    round((sale.total_sales
      - coalesce(direct.payments, 0)
      - coalesce(cheque.payments, 0)
      - greatest(
          coalesce(direct.deducted_wht, 0) + coalesce(cheque.deducted_wht, 0),
          coalesce(wht.amount, 0)
        ))::numeric, 2) as remaining
  from public.sales_view sale
  join collected_cheque_settlement cheque on cheque.invoice_id = sale.id::text
  left join direct_settlement direct on direct.invoice_id = sale.id::text
  left join recorded_wht wht on wht.invoice_no = sale.invoice_no::text
  where sale.document_type = 'INVOICE'
)
update public.cheque_allocations allocation
set cash_fraction = allocation.cash_fraction + residual.remaining
from residuals residual
where allocation.id = residual.final_allocation_id
  and residual.remaining > 0
  and residual.remaining < 1;

alter table public.customer_cheques add column if not exists collection_date date;
alter table public.customer_cheques add column if not exists bank_name text not null default '';
update public.customer_cheques set collection_date = coalesce(collection_date, cheque_date) where collection_date is null;
alter table public.customer_cheques alter column collection_date set not null;

do $$
declare
  old_record record;
  new_cheque_id bigint;
begin
  for old_record in
    select * from public.invoice_collections where payment_method = 'CHEQUE'
  loop
    select id into new_cheque_id
    from public.customer_cheques
    where legacy_collection_id = old_record.id;

    if new_cheque_id is null then
      insert into public.customer_cheques (
        customer_code, customer_name, collection_date, cheque_no, cheque_date, amount,
        cheque_status, cheque_status_date, notes, legacy_collection_id,
        created_at, updated_at
      ) values (
        old_record.customer_code, old_record.customer_name, old_record.collection_date,
        coalesce(old_record.reference_no, 'LEGACY-' || old_record.id),
        old_record.collection_date, old_record.amount,
        coalesce(old_record.cheque_status, 'IN_TREASURY'),
        coalesce(old_record.cheque_status_date, old_record.collection_date),
        old_record.notes, old_record.id, old_record.created_at, old_record.updated_at
      ) returning id into new_cheque_id;
    end if;

    insert into public.cheque_allocations (cheque_id, invoice_id, invoice_no, allocated_amount)
    values (new_cheque_id, old_record.invoice_id, old_record.invoice_no, old_record.amount)
    on conflict (cheque_id, invoice_id) do nothing;
  end loop;

  delete from public.invoice_collections where payment_method = 'CHEQUE';
end $$;
