create table if not exists public.wht_collections (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  invoice_no text not null,
  invoice_date date not null,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  tax numeric(14,2) not null default 0 check (tax >= 0),
  total numeric(14,2) generated always as (subtotal + tax) stored,
  wht_rate numeric(6,3) not null default 1,
  wht_amount numeric(14,2) generated always as (round(subtotal * wht_rate / 100, 2)) stored,
  collected_amount numeric(14,2) not null default 0 check (collected_amount >= 0),
  collection_date date,
  wht_group_id text,
  certificate_no text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wht_collections_customer_idx
  on public.wht_collections (customer_name);
create index if not exists wht_collections_invoice_idx
  on public.wht_collections (invoice_no);
create index if not exists wht_collections_date_idx
  on public.wht_collections (invoice_date);

alter table public.wht_collections enable row level security;
alter table public.wht_collections add column if not exists wht_group_id text;
alter table public.wht_collections add column if not exists certificate_no text;
alter table public.wht_collections add column if not exists sales_id text;
alter table public.wht_collections add column if not exists document_type text not null default 'INVOICE';
alter table public.wht_collections drop constraint if exists wht_collections_document_type_check;
alter table public.wht_collections add constraint wht_collections_document_type_check check (document_type in ('INVOICE', 'DR_NOTE'));
create unique index if not exists wht_collections_sales_id_unique on public.wht_collections (sales_id) where sales_id is not null;
create index if not exists wht_collections_group_idx on public.wht_collections (wht_group_id);
create index if not exists wht_collections_certificate_idx on public.wht_collections (certificate_no);

create table if not exists public.wht_collection_groups (
  id text primary key,
  customer_name text not null,
  certificate_no text,
  collection_date date not null,
  collected_amount numeric(14,2) not null check (collected_amount > 0),
  allocated_amount numeric(14,2) not null default 0 check (allocated_amount >= 0),
  unallocated_amount numeric(14,2) not null default 0 check (unallocated_amount >= 0),
  created_at timestamptz not null default now(),
  check (allocated_amount <= collected_amount + 0.01),
  check (abs((collected_amount - allocated_amount) - unallocated_amount) <= 0.01)
);
create index if not exists wht_collection_groups_customer_idx on public.wht_collection_groups (customer_name);
create index if not exists wht_collection_groups_date_idx on public.wht_collection_groups (collection_date);
alter table public.wht_collection_groups enable row level security;
revoke all on public.wht_collection_groups from anon, authenticated;
revoke all on public.wht_collections from anon, authenticated;
notify pgrst, 'reload schema';
