create table if not exists public.wht_collections (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  invoice_no text not null,
  invoice_date date not null,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  tax numeric(14,2) not null default 0 check (tax >= 0),
  total numeric(14,2) generated always as (subtotal + tax) stored,
  wht_rate numeric(6,3) not null default 1,
  wht_amount numeric(14,2) generated always as (round(subtotal * wht_rate / 100, 2)) stored,
  collected_amount numeric(14,2) not null default 0 check (collected_amount >= 0),
  collection_date date,
  wht_group_id text,
  certificate_no text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wht_collections_customer_idx
  on public.wht_collections (customer_name);
create index if not exists wht_collections_invoice_idx
  on public.wht_collections (invoice_no);
create index if not exists wht_collections_date_idx
  on public.wht_collections (invoice_date);

alter table public.wht_collections enable row level security;
alter table public.wht_collections add column if not exists wht_group_id text;
alter table public.wht_collections add column if not exists certificate_no text;
create index if not exists wht_collections_group_idx on public.wht_collections (wht_group_id);
create index if not exists wht_collections_certificate_idx on public.wht_collections (certificate_no);
revoke all on public.wht_collections from anon, authenticated;
notify pgrst, 'reload schema';
